Recover clang-format check not using docker img

diff --git a/.github/workflows/clangformat_check.yaml b/.github/workflows/clangformat_check.yaml
--- a/.github/workflows/clangformat_check.yaml
+++ b/.github/workflows/clangformat_check.yaml
@@ -9,9 +9,7 @@ on:
       - '*'
 
 env:
-  DOCKERFILE: docker/Dockerfile.linux
-  DOCKER_BUILDIMAGE: libcore-linux
-  DOCKER_BUILDIMAGE_WORKDIR: /mnt/workspace
+  BUILD_DEPENDENCIES: cmake build-essential checkinstall zlib1g-dev libssl-dev libfmt-dev clang-14
 
 jobs:
   clang-format-check:
@@ -23,25 +21,24 @@ jobs:
         uses: actions/checkout@v4
         with:
           ref: ${{ github.event.pull_request.head.sha }}
-          submodules: true
+          submodules: false
 
-      - name: Build docker image
+      - name: Install dependencies
         run: |
-          docker build -t ${{ env.DOCKER_BUILDIMAGE }}:latest -f ${{ env.DOCKERFILE }} .
+          sudo apt-get update && \
+          sudo apt-get install -y ${{ env.BUILD_DEPENDENCIES }}
 
       - name: Check clang-format
         run: |
-          docker run --rm -v $(pwd):${{ env.DOCKER_BUILDIMAGE_WORKDIR }} ${{ env.DOCKER_BUILDIMAGE }}:latest sh -c " \
-            FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
-            TMPFILE="./formatted_file"
-            for file in $FILES; do
-              sudo clang-format -style=file $file > $TMPFILE
-              if ! diff $file $TMPFILE > /dev/null; then
-                echo "Clang-format failed on $file"
-                sudo rm $TMPFILE
-                exit 1
-              fi 
-              sudo rm $TMPFILE
-            done
-          "
+          FILES=$(find . -not -path "./third_party/*" -not -path "./build/*" \( -name '*.cc' -o -name '*.c' -o -name '*.h' \))
+          TMPFILE="./formatted_file"
+          for file in $FILES; do
+            clang-format -style=file $file > $TMPFILE
+            if ! diff $file $TMPFILE > /dev/null; then
+              echo "Clang-format failed on $file"
+              rm $TMPFILE
+              exit 1
+            fi 
+            rm $TMPFILE
+          done
           echo "Clang-format check successful"
